trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: '5ad492c1-cb8e-424e-949c-c0b17f343564'

  # Web app name
  webAppName: 'hsonnlWebApp'

  poolName: 'hsonnlPool'
  # Agent VM image name
  vmImageName: 'hsonnlVM'

  # Environment name
  # environmentName: 'hsonnlEnv'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  # Python version: 3.7
  pythonVersion: '3.7'

name: Azure Pipelines
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: $(poolName)
      vmImage: $(vmImageName)
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          pwd
          git remote -v
          git fetch
          git pull origin master
          ls
        workingDirectory: $(projectRoot)
    # - task: Bash@3
    #   inputs:
    #     targetType: 'inline'
    #     script: |
    #       terraform init
    #       terraform force-unlock -force ce387184-ce0d-0544-1715-3e875e41ecdc
    #       terraform plan
    #       terraform destroy -auto-approve
    #     workingDirectory: ./terraform
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          terraform --version
          terraform init
          terraform plan
          terraform apply -auto-approve
        workingDirectory: ./terraform
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: '~/.ssh/id_rsa.pub'
        sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQFgNczfMpJKcrXI07XfxbXfFxhqEY6p7RZ33RYpbX2zM6w7F9icesg5xP20/HfshDuNTvWMEHo3G5g0rOVtfXfH0EBPh2Fadzul5JK6Dskznz8NAI8anjKuyvjRbmV+CeJeIAGE6qRMCzJpzDLVfPcz1DIf0b/9wdinDcTZbgNDH99NRWjd9eRmuak8SVV5suqYYrBlzmrxNYBoF2CJQoGjuDBp4fWgH1Qmt2a814jP++eVLEcVrhXlODyDLxrxmN5UFu10HytGJcGQi6sefclTEKf580dtek6bLOrL+jTQb7BLZFC43d5bnXmileB0fUB5OYwv+nn+r5FsafpR4Q/KbVNSSX6GDkBOK5nRgUUkPFMID5mK+8Evu+0heANmX9i4DMUVirIqaDdetGo+enacJ0rET2tdf22mtBBeQ1i8HW2tWm/9a38tDwoYf9kx0n7bBec/gK+erM+x1UBsqZ7PZgiF/CccN4H1q5iPwLGupzr5STixdxPhx/qhgZOrk= hsonnl@hsonnlVM'
        sshKeySecureFile: 'id_rsa'
    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: './automatedtesting/jmeter/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload Package'
      artifact: drop-fakerestapi
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: './/automatedtesting'
        artifact: 'automatedtesting'
        publishLocation: 'pipeline'
        workingDirectory: $(projectRoot)
- stage: Deployment
  jobs:
  - deployment: FakeRestAPI
    pool:
      name: $(poolName)
      vmImage: $(vmImageName)
    environment:
      name:  'hsonnlEnv'
      resourceName: 'hsonnlVM'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appType: 'webApp'
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip'
              deploymentMethod: 'auto'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # install ZIP
                sudo apt-get update -y
                sudo apt-get -y install zip
                sudo apt-get -y install python3-pip
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # install JAVA, APACHE2
                sudo apt-get update -y
                sudo apt-get install openjdk-8-jdk -y
                sudo apt-get install apache2 -y
                sudo systemctl start apache2
                sudo systemctl enable apache2
          - task: JMeterInstaller@0
            inputs:
              jmeterVersion: '5.4.2'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                sudo apt-get install python default-jre-headless python-pip python-dev libxml2-dev libxslt-dev zlib1g-dev -y
                sudo pip install bzt
          # - task: TaurusInstaller@0
          #   inputs:
          #     taurusVersion: '1.15.3'
          #     pythonCommand: 'python3'
          - task: TaurusRunner@0
            inputs:
              taurusConfig: |
                execution:
                - scenario:
                    # You can also reference a JMeter test plan (recommended)
                    script: $(Pipeline.Workspace)/automatedtesting/jmeter/Starter.jmx
                  concurrency: 5
                  iterations: 10
                  ramp-up: 2s
                
                reporting:
                - module: junit-xml
                  filename: my-taurus-output-2/TEST-Taurus.xml
              jmeterHome: '$(JMeterInstaller.JMeterHome)'
              jmeterPath: '$(JMeterInstaller.JMeterPath)'
              jmeterVersion: '$(JMeterInstaller.JMeterVersion)'
              outputDir: 'my-taurus-output-2'
  - deployment: VMDeploy
    displayName: web
    environment:
      name:  'hsonnlEnv'
      resourceName: 'hsonnlVM'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                #! /bin/bash
                
                sudo apt-get upgrade -y
                sudo apt-get install unzip -y
                sudo apt-get install -y chromium-browser
                sudo apt-get install chromium-chromedriver -y
                pip3 install selenium
                pip install selenium
                echo 'export PATH=$PATH:/path/to/driver' >> ~/.bash_profile
                source ~/.bash_profile
                
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Run selenium
                
                git clone https://github.com/nguyenlehaison/my-azure-project-03.git
                cd ./my-azure-project-03/
                git pull
                cd ./automatedtesting/selenium/
                python3 login.py
- stage: Postman
  jobs:
  - job: Postman
    pool:
      name: $(poolName)
      vmImage: $(vmImageName)
    steps:
    - task: CmdLine@2
      displayName: Install Newman
      inputs:
        script: 'sudo npm install -g newman'
        workingDirectory: $(System.DefaultWorkingDirectory)
    - task: CmdLine@2
      displayName: Run Regression Tests
      continueOnError: true
      inputs:
        script: 'newman run StarterAPIs.json  --reporters cli,junit --reporter-junit-export junit-report.xml'

        workingDirectory: './automatedtesting/postman'
    - task: PublishTestResults@2
      displayName: 'Publish Test Results for postman'
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/*.xml'
        mergeTestResults: true
        failTaskOnFailedTests: false